spring.application.name=control-gastos-app
server.port = 8081
spring.thymeleaf.enabled=true


spring.datasource.url=jdbc:mysql://localhost:3306/finflow
spring.datasource.username=nommbre
spring.datasource.password=contra



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false